### PR TITLE
Add basic end-to-end test

### PR DESCRIPTION
**Pull request by SaschaMann**
(see #25)

### CODE REVIEW

**Comment by SaschaMann** [comment]
Seems to fail as expected :) 

---

Should be squashed on merge.

**Review by DilumAluthge — APPROVED** [review]
Can you add a test beforehand that checks that the test output file does not exist before we run the tests?

Apart from that looks good to me!

**Review by DilumAluthge — DISMISSED** [review]
LGTM. Feel free to merge when you're ready.

**Comment by SaschaMann** [comment]
> LGTM. Feel free to merge when you're ready.

I just changed the branch protection to dismiss stale reviews, I'll disable it for now. Sorry for the notification noise :D

**Comment by SaschaMann** [comment]
Ok now it works, if you could hit approve once more, I'd be grateful :) (sorry for the spam!)

**Review by DilumAluthge — APPROVED** [review]
Done.

No worries! I actually like the "auto-dismiss stale reviews" setting personally.

**Pull request merged**
